<?php
/**
 * Created by PhpStorm.
 * User: Miinno-10
 * Date: 2017/9/1
 * Time: 11:16
 */
namespace activity\anniu\web\controllers;


use activity\anniu\models\Userinfo;
use Yii;
use yii\helpers\Url;
use yii\helpers\Json;
use yii\web\Controller;

class DefaultController extends Controller
{
    public $enableCsrfValidation = false;

    public function init()
    {
        parent::init();
        $this->view->title = Yii::$app->params['site_name'];
    }

    public function beforeAction($action)
    {
        if (Yii::$app->user->isGuest) {
            return $this->redirect(Url::to(['oauth/index', 'forword' => urlencode(Url::current([], true))], true));
        }

        return parent::beforeAction($action); // TODO: Change the autogenerated stub

    }

    /**
     *报名接口请求
     * @return string
     */
    public function actionCreate()
    {
        //接收值
        $request = Yii::$app->request;
        $callback = $request->get('callback');
        $model = new Userinfo();
        $openid = isset(Yii::$app->user->identity->openid) ? Yii::$app->user->identity->openid : '';
        $model->openid = $openid;

        if ($request->isGet) {
            if ($model->load($request->get(), '') && $model->save()) {

                $result = [
                    'code' => 0,
                    'desc' => '添加成功',
                ];
            } else {

                $result = [
                    'code' => 1,
                    'desc' => $model->getErrors(),
                ];
            }
        } else {
            $result = [
                'code' => 1,
                'desc' => '请求方式错误',
            ];
        }
        $result = Json::encode($result);

        return $callback . '(' . $result . ')';
    }


}