<?php
/**
 * Created by PhpStorm.
 * User: ezsky
 * Date: 2017/4/14
 * Time: 上午1:56
 */

namespace grazio\core\components;


class WebController extends \yii\web\Controller
{
    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
        $this->setViewPath($this->module->basePath . '/web/views'. DIRECTORY_SEPARATOR . $this->id);
    }
}